server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false     #是否向注册中心注册自己
    fetch-registry: false     #fetch-registry: false表示自己为注册中心
    service-url:
      ##单机：项目访问eureka的地址 默认为8761  监控页面
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群： 需要关联别人  注意这里填的是别人的eureka的访问地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/